hybrid cache implementations
adzhiasan/HybridCache pull request #1
Opened 2024-06-22 16:48 UTC by adzhiasan

2024-07-02 15:19 UTC, aryabush requested changes

2024-07-02 15:19 UTC, aryabush commented on HybridCache.Tests/HybridCacheTests.cs
> +        resultValue.Should().Be(cachedValue);
Множественные асерты это запах. В данном случае, мое мнение, что достаточно проверки resultValue.Should().Be(cachedValue); Если хотим проверить что в случае кеширования в редисе не ходили в бд, то это стоит сделать отдельным тестом

2024-07-02 15:19 UTC, aryabush commented on HybridCache.Tests/HybridCacheTests.cs
> +        resultValue.Should().Be(valueFromDataStorage);
тут аналогично комменту про множественные асерты

2024-07-02 15:19 UTC, aryabush commented on HybridCache.Tests/HybridCacheTests.cs
> +public class HybridCacheTests
Кажется не хватает тестов на граничные значения, когда value = null

2024-07-02 15:19 UTC, aryabush commented on HybridCache/HybridCache.cs
> +    public T? GetOrAdd<T>(string key, Func<T?> itemProvider, TimeSpan ttl)
метод должен быть асинхронный

2024-07-02 15:19 UTC, aryabush commented on Services/ProductsController.cs
> +        var products = _hybridCache.GetOrAdd(
Сервис сделали полностью синхронным. Так не стоит делать.

2024-07-05 14:37 UTC, aryabush commented on HybridCache/IRedisCacheAdapter.cs
> +                value = JsonSerializer.Deserialize<T?>(cachedValue);
Что будет если мы серелизуем положим в кеш, дальше катнем релиз в котором поменяем стурктуру кешируемого объекта, так что он больше не сможет десерелизоваться объект, который мы похранили в экземпляр нового класса?

2024-07-08 09:08 UTC, adzhiasan commented on HybridCache/IRedisCacheAdapter.cs
> +                value = JsonSerializer.Deserialize<T?>(cachedValue);
Упадёт ошибка десериализации.
Однако мы считаем, что соответствие контракту – это обязанность клиента гибридного кэша, а не самого кэша.

2024-07-12 15:40 UTC, aryabush commented on HybridCache/IRedisCacheAdapter.cs
> +                value = JsonSerializer.Deserialize<T?>(cachedValue);
кеш не должен падать, если структура кешируемого объекта поменялась. Тут он должен повторять поведение ин мемори кеша. Его цель обеспечить по возможности (!) получение данных без похода в бд. Если такой возможности нет, то мы должны не падать, а сходить в БД и вернуть данные

2024-07-12 16:12 UTC, aryabush commented on Services/ProductsController.cs
> +        return await _hybridCache.GetOrAddAsync(
тут нет причин делать await. достаточно убрать async из public Task<IEnumerable<Product>?> GetProductsAsync(

2024-07-12 17:57 UTC, aryabush commented
Осталось получается два коммента в остальном все 🔥

2024-07-15 16:28 UTC, aryabush approved these changes

2024-07-18 15:27 UTC, aryabush approved these changes

2024-07-22 04:31 UTC, closed without merging